### ISSUE TITLE
feat: Report need

### ISSUE THREAD

**Issue by jingyuexing** [nonebot/nonebug#12]
The official document does not say the test report, so how to know the test situation?

Maybe there should be a report like this one：
| test name |  test status |
|:-----------:|:------------:|
|  XXX         |   PASS         |
|    VVVVVV|   NO PASS |

total pass:  1
total reject: 1

**Comment by yanyongyu** [comment]
？你用过pytest吗

**Comment by jingyuexing** [comment]
> ？你用过pytest吗 ![image](https://user-images.githubusercontent.com/42488585/238539794-2c1a6574-d7e1-4934-ac81-8d063decef02.png)

机器人自己出局报告 而不是单单的命令行的报告

**Comment by jingyuexing** [comment]
> ？你用过pytest吗 ![image](https://user-images.githubusercontent.com/42488585/238539794-2c1a6574-d7e1-4934-ac81-8d063decef02.png)

机器人自己出局截图形式的报告或者其他的

**Comment by yanyongyu** [comment]
你是不是对测试有什么误解
