### ISSUE TITLE
0.4.1 需要 asyncio_mode = "auto"

### ISSUE THREAD

**Issue by xyqyear** [nonebot/nonebug#31]
由于 0984b58 的修改，现在需要 `asyncio_mode = "auto"`，`nonebug_init` 才会起作用。

建议要么写到文档里，要么回滚修改。

**Comment by yanyongyu** [comment]
https://github.com/nonebot/nonebot2/pull/3087

**Comment by yanyongyu** [comment]
后续可能还有些改动会一起加到文档
